apiVersion: v1
kind: Service
metadata:
  name: ph-static-h5
  namespace: xinfa
  labels:
    app: ph-static-h5
    tier: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: ph-static-h5
    tier: frontend
