apiVersion: v1
kind: Service
metadata:
  name: xf-static-web
  namespace: xinfa
  labels:
    app: xf-static-web
    tier: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: xf-static-web
    tier: frontend
