image: docker:20.10.16
services:
  - name: docker:20.10.16-dind
    alias: docker
    command: [ "--tls=false" ]
variables:
   DOCKER_DRIVER: overlay2
   DOCKER_TLS_CERTDIR: ""
   DOCKER_HOST: tcp://docker:2375
   NAMESPACE: xinfa

default:
  tags:
    - xinfa-runner

.build-projects:
  stage: build
  cache:
    paths:
      - node_modules
  image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/node:16.17.0
  artifacts:
   untracked: true
   expire_in: 24 hrs
   exclude:
     - $CI_PROJECT_DIR/$PROJECT/node_modules/**/*
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "p8s1"'
      changes:
        - $PROJECT/**/*

.docker-build:
  stage: build-image
  script:
    - cd $PROJECT
    - docker login -u $CI_DEPENDENCY_PROXY_USER -p $CI_DEPENDENCY_PROXY_PASSWORD $CI_DEPENDENCY_PROXY_SERVER
    - docker build --build-arg image_proxy=$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX -t $IMAGE_NAME -t $IMAGE_NAME-$(date +%s) . --no-cache
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push -a $CI_REGISTRY_IMAGE
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$IMAGE_TAG-dev
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "p8s1"'
      variables:
        IMAGE_NAME: $CI_REGISTRY_IMAGE:$IMAGE_TAG-$CI_COMMIT_REF_NAME-prod
      changes:
        - $PROJECT/**/*

stages:
  - build
  - build-image

build-image-pt-launch:
  extends: .docker-build
  variables:
    IMAGE_TAG: pt-launch

#===============================================================================================

build-image-site-download:
  extends: .docker-build
  variables:
    IMAGE_TAG: site-download

#===============================================================================================

build-ph-static-h5:
  extends: .build-projects
  script:
    - cd ph-static-h5
    - npm install
    - npm install -g @quasar/cli
    - quasar build
  variables:
    IMAGE_TAG: ph-static-h5

build-image-ph-static-h5:
  extends: .docker-build
  variables:
    IMAGE_TAG: ph-static-h5
  needs:
    - build-ph-static-h5

#===============================================================================================

build-ph-static-web:
  extends: .build-projects
  script:
    - cd ph-static-web
    - npm install
    - npm run build
  variables:
    IMAGE_TAG: ph-static-web

build-image-ph-static-web:
  extends: .docker-build
  variables:
    IMAGE_TAG: ph-static-web
  needs:
    - build-ph-static-web

#===============================================================================================

build-tf-manager-web:
  extends: .build-projects
  script:
    - cd tf-manager-web
    - npm install
    - npm run build:prod
  variables:
    IMAGE_TAG: tf-manager-web

build-image-tf-manager-web:
  extends: .docker-build
  variables:
    IMAGE_TAG: tf-manager-web
  needs:
    - build-tf-manager-web

#===============================================================================================

build-xf-static-h5:
  extends: .build-projects
  script:
    - cd xf-static-h5
    - npm install
    - npm i process
    - npm install -g @quasar/cli
    - quasar build
  variables:
    IMAGE_TAG: xf-static-h5

build-image-xf-static-h5:
  extends: .docker-build
  variables:
    IMAGE_TAG: xf-static-h5
  needs:
    - build-xf-static-h5

#===============================================================================================

build-xf-static-web:
  extends: .build-projects
  script:
    - cd xf-static-web
    - npm install
    - npm run build
  variables:
    IMAGE_TAG: xf-static-web

build-image-xf-static-web:
  extends: .docker-build
  variables:
    IMAGE_TAG: xf-static-web
  needs:
    - build-xf-static-web

#===============================================================================================

build-dy-static-h5:
  extends: .build-projects
  script:
    - cd dy-static-h5
    - npm install
    - npm i process
    - npm install -g @quasar/cli
    - quasar build
  variables:
    IMAGE_TAG: dy-static-h5

build-image-dy-static-h5:
  extends: .docker-build
  variables:
    IMAGE_TAG: dy-static-h5
  needs:
    - build-dy-static-h5

#===============================================================================================

build-dy-static-web:
  extends: .build-projects
  script:
    - cd dy-static-web
    - npm install
    - npm run build
  variables:
    IMAGE_TAG: dy-static-web

build-image-dy-static-web:
  extends: .docker-build
  variables:
    IMAGE_TAG: dy-static-web
  needs:
    - build-dy-static-web
