image: docker:20.10.16
services:
  - name: docker:20.10.16-dind
    alias: docker
    command: [ "--tls=false" ]
variables:
   DOCKER_DRIVER: overlay2
   DOCKER_TLS_CERTDIR: ""
   DOCKER_HOST: tcp://docker:2375

default:
  tags:
    - jolly88-complex-runners

.build-h5:
  script:
    - cd $PROJECT
    - npm install
    - npm install -g @quasar/cli
    - quasar build

.build-web:
  script:
    - cd $PROJECT
    - npm install
    - npm run build

.p8s0-rules:
  rules:
    - &p8s0-rules
      if: '$CI_COMMIT_BRANCH == "prod/p8s0"'
      changes:
        - $PROJECT/**/*

.p8s1-rules:
  rules:
    - &p8s1-rules
      if: '$CI_COMMIT_BRANCH == "prod/p8s1"'
      changes:
        - $PROJECT/**/*

.build-projects:
  stage: build
  cache:
    paths:
      - node_modules
  image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/node:16.17.0
  artifacts:
   untracked: true
   expire_in: 24 hrs
   exclude:
     - $CI_PROJECT_DIR/$PROJECT/node_modules/**/*
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "prod/p8s0" || $CI_COMMIT_BRANCH == "prod/p8s1"'
#      changes:
#        - $PROJECT/**/*

.docker-build:
  stage: build-image
  script:
    - cd $PROJECT
    - docker login -u $CI_DEPENDENCY_PROXY_USER -p $CI_DEPENDENCY_PROXY_PASSWORD $CI_DEPENDENCY_PROXY_SERVER
    - docker build --build-arg image_proxy=$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX -t $CI_REGISTRY_IMAGE:$PROJECT-${CI_COMMIT_REF_NAME/\//-}-$(date +%s) . --no-cache
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push -a $CI_REGISTRY_IMAGE
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "prod/p8s0" || $CI_COMMIT_BRANCH == "prod/p8s1"'
#      changes:
#        - $PROJECT/**/*

stages:
  - build
  - build-image

build-image-pt-launch:
  extends: .docker-build
  variables:
    PROJECT: pt-launch
  rules:
    - <<: *p8s0-rules
    - <<: *p8s1-rules

#===============================================================================================

build-image-dy-download:
  extends:
    - .docker-build
    - .p8s0-rules
  variables:
    PROJECT: dy-download

#===============================================================================================

build-image-xf-maintenance:
  extends:
    - .docker-build
    - .p8s1-rules
  variables:
    PROJECT: xf-maintenance

#===============================================================================================

build-tf-manager-web:
  extends:
    - .build-projects
    - .build-web
  variables:
    PROJECT: tf-manager-web
  rules:
    - <<: *p8s0-rules
    - <<: *p8s1-rules

build-image-tf-manager-web:
  extends: .docker-build
  variables:
    PROJECT: tf-manager-web
  needs:
    - build-tf-manager-web
  rules:
    - <<: *p8s0-rules
    - <<: *p8s1-rules

#===============================================================================================

build-xf-static-h5:
  extends:
    - .build-projects
    - .build-h5
    - .p8s1-rules
  variables:
    PROJECT: xf-static-h5

build-image-xf-static-h5:
  extends:
    - .docker-build
    - .p8s1-rules
  variables:
    PROJECT: xf-static-h5
  needs:
    - build-xf-static-h5

#===============================================================================================

build-xf-static-web:
  extends:
    - .build-projects
    - .build-web
    - .p8s1-rules
  variables:
    PROJECT: xf-static-web

build-image-xf-static-web:
  extends:
    - .docker-build
    - .p8s1-rules
  variables:
    PROJECT: xf-static-web
  needs:
    - build-xf-static-web

#===============================================================================================

build-dy-static-h5:
  extends:
    - .build-projects
    - .build-h5
    - .p8s0-rules
  variables:
    PROJECT: dy-static-h5

build-image-dy-static-h5:
  extends:
    - .docker-build
    - .p8s0-rules
  variables:
    PROJECT: dy-static-h5
  needs:
    - build-dy-static-h5

#===============================================================================================

build-dy-static-web:
  extends:
    - .build-projects
    - .build-web
    - .p8s0-rules
  variables:
    PROJECT: dy-static-web

build-image-dy-static-web:
  extends:
    - .docker-build
    - .p8s0-rules
  variables:
    PROJECT: dy-static-web
  needs:
    - build-dy-static-web


#===============================================================================================

build-dy-static-new-h5:
  extends:
    - .build-projects
    - .build-h5
    - .p8s0-rules
  variables:
    PROJECT: dy-static-new-h5

build-image-dy-static-new-h5:
  extends:
    - .docker-build
    - .p8s0-rules
  variables:
    PROJECT: dy-static-new-h5
  needs:
    - build-dy-static-new-h5

#===============================================================================================

build-affiliate-static-web:
  extends:
    - .build-projects
    - .build-web
  script:
    - cd $PROJECT
    - npm install
    - npm run build:prod
  variables:
    PROJECT: affiliate-static-web
  rules:
    - <<: *p8s0-rules
    - <<: *p8s1-rules

build-image-affiliate-static-web:
  extends: .docker-build
  variables:
    PROJECT: affiliate-static-web
  needs:
    - build-affiliate-static-web
  rules:
    - <<: *p8s0-rules
    - <<: *p8s1-rules