apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ph-static-web
  namespace: xinfa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ph-static-web
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
