export const ResponseCode = {
  SUCCESS: 0,
  ERROR_SYSTEM: 500,
  TOO_OFTEN_REQUEST: 504,
  ERROR_BAD_REQUEST: 400,
  ERROR_UNAUTHORIZED: 401,
  ERROR_FORBIDDEN: 403,
  ERROR_NOT_FOUND: 404,
  ERROR_METHOD_NOT_SUPPORT: 405,
  ERROR_LOGIN_INVALID_SESSION: 501,
  ERROR_LOGIN_EXPIRED_SESSION: 502,
  ERROR_PASS_REPEAT: 600,
  ERROR_NAME_EXIST: 601,
  ERROR_TOKEN_EXPIRED: 602,
  ERROR_TOKEN_MISSED: 603,
  ERROR_TOKEN_LOGGED: 604,
  ERROR_USER_TOO_FAST: 608,
  ERROR_EMPTY_ADS: 908,
  ERROR_AMOUNT_DEPOSIT: 11003,
  ERROR_AMOUNT_PRIVILEGE_DEPOSIT: 11004,
  ERROR_PROMO_NOT_STARTED: 31000,
  ERROR_PROMO_USER_NOT_MEET_REQUIREMENT: 35000,
  ERROR_PROMO_CLAIMED: 35001,
  ERROR_PROMO_NOT_IN_RANGE: 37001
};

const skipCode = [11002, 1312];

export function SkipErrorCode(code) {
  for (let i = 0; i < skipCode.length; i++) {
    if (skipCode[i] === code) {
      return 1;
    }
  }
  return 0;
}

export const GLOBAL_NOTIFICATION_ERROR_CODE = [
  ResponseCode.ERROR_USER_TOO_FAST,
  ResponseCode.ERROR_PROMO_NOT_STARTED,
  ResponseCode.ERROR_PROMO_USER_NOT_MEET_REQUIREMENT,
  ResponseCode.ERROR_PROMO_CLAIMED,
  ResponseCode.ERROR_PROMO_NOT_IN_RANGE,
  ResponseCode.ERROR_SYSTEM
];
