---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xf-static-h5
  namespace: xinfa
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
    - hosts:
        - xf-h5.jolly88-ph01.com
      secretName: xf-static-h5
  rules:
  - host: xf-h5.jolly88-ph01.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: xf-static-h5
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: xf-static-h5
  namespace: xinfa
  labels:
    app: xf-static-h5
    tier: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: xf-static-h5
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xf-static-h5
  namespace: xinfa
  labels:
    app: xf-static-h5
    tier: frontend
spec:
  selector:
    matchLabels:
      app: xf-static-h5
      tier: frontend
  template:
    metadata:
      labels:
        app: xf-static-h5
        tier: frontend
    spec:
      containers:
        - name: xf-static-h5
          image: git.caspen-tech.com:5050/jolly88-complex/frontend:xf-static-h5
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: Asia/Singapore
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
      imagePullSecrets:
        - name: gitlab-registry
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: xf-static-h5
  namespace: xinfa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xf-static-h5
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
