apiVersion: apps/v1
kind: Deployment
metadata:
  name: dy-static-h5
  namespace: xinfa
  labels:
    app: dy-static-h5
    tier: frontend
spec:
  selector:
    matchLabels:
      app: dy-static-h5
      tier: frontend
  template:
    metadata:
      labels:
        app: dy-static-h5
        tier: frontend
    spec:
      containers:
        - name: dy-static-h5
          image: git.caspen-tech.com:5050/jolly88-complex/frontend:dy-static-h5-1687347052 # {"$imagepolicy": "xinfa:dy-static-h5"}
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: Asia/Singapore
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - dy-static-h5
              topologyKey: kubernetes.io/hostname
      imagePullSecrets:
        - name: gitlab-registry
