export const BET_STATUS = {
  SETTLE: "SETTLE",
  SETTLED: "SETTLED",
  BET_N_SETTLE: "BET_N_SETTLE",
  CANCEL: "CANCEL",
  ROLLBACK: "ROLLBACK",
  PATCH: "PATCH",
  BET: "BET",
  UNSETTLED: "UNSETTLED",
  JACKPOT: "JACKPOT",
  BONUS: "BONUS"
};
