---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ph-static-web
  namespace: xinfa
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
    - hosts:
        - ph-web.jolly88-ph01.com
      secretName: ph-static-web
  rules:
  - host: ph-web.jolly88-ph01.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ph-static-web
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ph-static-web
  namespace: xinfa
  labels:
    app: ph-static-web
    tier: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: ph-static-web
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-static-web
  namespace: xinfa
  labels:
    app: ph-static-web
    tier: frontend
spec:
  selector:
    matchLabels:
      app: ph-static-web
      tier: frontend
  template:
    metadata:
      labels:
        app: ph-static-web
        tier: frontend
    spec:
      containers:
        - name: ph-static-web
          image: git.caspen-tech.com:5050/jolly88-complex/frontend:ph-static-web
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: Asia/Singapore
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - ph-static-web
              topologyKey: kubernetes.io/hostname
      imagePullSecrets:
        - name: gitlab-registry
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ph-static-web
  namespace: xinfa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ph-static-web
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ph-static-web
  namespace: xinfa
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ph-static-web
