gitops:
  manifest_projects:
  - id: "jolly88-complex/frontend"
    ref:
      branch: master
    default_namespace: xinfa
    paths:
    - glob: '/**/*.yml'

ci_access:
  projects:
    - id: "jolly88-complex/frontend"
      default_namespace: xinfa