gitops:
  manifest_projects:
  - id: "jolly88-complex/frontend"
    ref:
      branch: master
    default_namespace: xinfa
    paths:
    - glob: '/**/*.{yaml,yml,json}'

ci_access:
  groups:
    - id: "jolly88-complex"
      default_namespace: xinfa