export const HOT_GAME_LIST = [
  {
    id: 23,
    name: "Aviator",
    code: "27",
    status: "OPEN",
    icon: "5/Spribe/4457f1e2-d1ea-4b53-a111-95a225bef685.png",
    sequence: 1,
    siteName: null,
    platformId: 16,
    platformName: "TFGaming",
    platformCode: "TFGaming",
    gameType: "SLOT",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "TFGaming"
  },
  {
    id: 61,
    name: "Pirate Flip",
    code: "32",
    status: "OPEN",
    icon: "8/TFGaming/32.png",
    sequence: 2,
    siteName: null,
    platformId: 16,
    platformName: "TFGaming",
    platformCode: "TFGaming",
    gameType: "SLOT",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "TFGaming"
  },
  {
    id: 64,
    name: "Mines",
    code: "229",
    status: "OPEN",
    icon: "11/JILI/c77236e7-a298-488a-975d-c1fd7f8e30f2.jpg",
    sequence: 3,
    siteName: null,
    platformId: 8,
    platformName: "JiliGames",
    platformCode: "JILI",
    gameType: "SLOT",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "JILI"
  },
  {
    id: 65,
    name: "7up7down",
    code: "124",
    status: "OPEN",
    icon: "11/JILI/9d163d59-27cc-4df7-8709-d2a2ecc0e65e.png",
    sequence: 4,
    siteName: null,
    platformId: 8,
    platformName: "JiliGames",
    platformCode: "JILI",
    gameType: "SLOT",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "JILI"
  },
  {
    id: 62,
    name: "Dragon & Tiger",
    code: "123",
    status: "OPEN",
    icon: "11/JILI/d3ec422a-bb04-4d7a-b9a9-e54fbdcae042.png",
    sequence: 5,
    siteName: null,
    platformId: 8,
    platformName: "JiliGames",
    platformCode: "JILI",
    gameType: "SLOT",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "JILI"
  },
  {
    id: 63,
    name: "Color Game",
    code: "197",
    status: "OPEN",
    icon: "11/JILI/86ae93d2-1e8d-4eb8-8b67-ce9db4e74ea6.png",
    sequence: 6,
    siteName: null,
    platformId: 8,
    platformName: "JiliGames",
    platformCode: "JILI",
    gameType: "SLOT",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "JILI"
  },
  { code: "WCEvo", platform: "WCEvo", type: "platform", name: "" },
  {
    id: 46,
    name: "Sic Bo",
    code: "125",
    status: "OPEN",
    icon: "11/JILI/e69c37b0-5925-43e1-b02a-3c63ac25add0.png",
    sequence: 8,
    siteName: null,
    platformId: 8,
    platformName: "JiliGames",
    platformCode: "JILI",
    gameType: "SLOT",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "JILI"
  },
  {
    id: 47,
    name: "Money Coming",
    code: "51",
    status: "OPEN",
    icon: "11/JILI/51.png",
    sequence: 9,
    siteName: null,
    platformId: 8,
    platformName: "JiliGames",
    platformCode: "JILI",
    gameType: "SLOT",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "JILI"
  },
  {
    id: 48,
    name: "Andar Bahar",
    code: "79",
    status: "OPEN",
    icon: "11/JILI/5d214dcd-08fb-4c54-b808-12c55ac19473.png",
    sequence: 10,
    siteName: null,
    platformId: 8,
    platformName: "JiliGames",
    platformCode: "JILI",
    gameType: "POKER",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "JILI"
  },
  {
    id: 49,
    name: "Dinosaur Tycoon",
    code: "42",
    status: "OPEN",
    icon: "11/JILI/42.png",
    sequence: 11,
    siteName: null,
    platformId: 8,
    platformName: "JiliGames",
    platformCode: "JILI",
    gameType: "FISH",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "JILI"
  },
  {
    id: 50,
    name: "Ludo Quick",
    code: "163",
    status: "OPEN",
    icon: "11/JILI/acd9b0fd-625d-4fb2-ae19-5e69b34e6700.png",
    sequence: 12,
    siteName: null,
    platformId: 8,
    platformName: "JiliGames",
    platformCode: "JILI",
    gameType: "POKER",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "JILI"
  },
  {
    id: 51,
    name: "Fortune Gems 2",
    code: "223",
    status: "OPEN",
    icon: "11/JILI/109.png",
    sequence: 13,
    siteName: null,
    platformId: 8,
    platformName: "JiliGames",
    platformCode: "JILI",
    gameType: "SLOT",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "JILI"
  },
  {
    id: 53,
    name: "Bombing Fishing",
    code: "20",
    status: "OPEN",
    icon: "11/JILI/20.png",
    sequence: 14,
    siteName: null,
    platformId: 8,
    platformName: "JiliGames",
    platformCode: "JILI",
    gameType: "FISH",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "JILI"
  },
  {
    id: 54,
    name: "Happy Fishing",
    code: "82",
    status: "OPEN",
    icon: "11/JILI/82.png",
    sequence: 15,
    siteName: null,
    platformId: 8,
    platformName: "JiliGames",
    platformCode: "JILI",
    gameType: "FISH",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "JILI"
  },
  {
    id: 55,
    name: "Plinko",
    code: "242",
    status: "OPEN",
    icon: "11/JILI/c936c03d-316d-4fb8-804a-9e9ca837aa90.png",
    sequence: 16,
    siteName: null,
    platformId: 8,
    platformName: "JiliGames",
    platformCode: "JILI",
    gameType: "SLOT",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "JILI"
  },
  {
    id: 56,
    name: "Jackpot Fishing",
    code: "32",
    status: "OPEN",
    icon: "11/JILI/32.png",
    sequence: 17,
    siteName: null,
    platformId: 8,
    platformName: "JiliGames",
    platformCode: "JILI",
    gameType: "FISH",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "JILI"
  },
  {
    id: 57,
    name: "Baccarat",
    code: "152",
    status: "OPEN",
    icon: "11/JILI/ba81c2f8-dcaa-4de0-982c-7e198fa3c8fe.png",
    sequence: 18,
    siteName: null,
    platformId: 8,
    platformName: "JiliGames",
    platformCode: "JILI",
    gameType: "POKER",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "JILI"
  },
  {
    id: 26,
    name: "TeenPatti 20-20",
    code: "161",
    status: "OPEN",
    icon: "11/JILI/c3a5ab4f-19f8-4299-b046-1fc4ea38ef4c.png",
    sequence: 19,
    siteName: null,
    platformId: 8,
    platformName: "JiliGames",
    platformCode: "JILI",
    gameType: "POKER",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "JILI"
  },
  {
    id: 25,
    name: "All-star Fishing",
    code: "119",
    status: "OPEN",
    icon: "11/JILI/119.png",
    sequence: 20,
    siteName: null,
    platformId: 8,
    platformName: "JiliGames",
    platformCode: "JILI",
    gameType: "FISH",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "JILI"
  },
  {
    id: 4,
    name: "Teen Patti",
    code: "72",
    status: "OPEN",
    icon: "11/JILI/097df233-0329-427c-a596-9af968062624.png",
    sequence: 21,
    siteName: null,
    platformId: 8,
    platformName: "JiliGames",
    platformCode: "JILI",
    gameType: "POKER",
    device: null,
    gameLabel: "HOT",
    updateBy: null,
    updateTime: null,
    type: "game",
    platform: "JILI"
  }
];

export const SLOT_LIST = [
  {
    id: 8,
    name: "JiliGames",
    code: "JILI",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT,FISH",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "JiliGames",
    sequence: 1
  },
  {
    id: 124,
    name: "Turbo",
    code: "Turbo",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: null,
    sequence: 2
  },
  {
    id: 21,
    name: "PG",
    code: "PG",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "Relax Gaming",
    sequence: 3
  },
  {
    id: 51,
    name: "JOKER",
    code: "JOKER",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT,FISH",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "JOKER",
    sequence: 4
  },
  {
    id: 31,
    name: "JDB",
    code: "JDB",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT,FISH",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: null,
    sequence: 5
  },
  {
    id: 107,
    name: "Big time Gaming",
    code: "WCBTG",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "Big Time",
    sequence: 6
  },
  {
    id: 111,
    name: "Relax",
    code: "WCRelax",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "Relax Gaming",
    sequence: 7
  },
  {
    id: 16,
    name: "TFGaming",
    code: "TFGaming",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "CASUAL",
    followType: "NEW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: null,
    sequence: 999
  },
  {
    id: 106,
    name: "No limit city",
    code: "WCNLC",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "No Limit City",
    sequence: 999
  },
  {
    id: 108,
    name: "Wazdan",
    code: "WCWazdan",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "Wazdan",
    sequence: 999
  },
  {
    id: 104,
    name: "Netent",
    code: "WCNetent",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "Netent",
    sequence: 999
  },
  {
    id: 105,
    name: "Red tiger",
    code: "WCRT",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "Red Tiger",
    sequence: 999
  },
  {
    id: 109,
    name: "One touch",
    code: "WCOTS",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "One Touch Slot",
    sequence: 999
  },
  {
    id: 120,
    name: "World Match",
    code: "WCWM",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "World Match",
    sequence: 999
  },
  {
    id: 113,
    name: "PNG",
    code: "WCPNG",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "PNG",
    sequence: 999
  },
  {
    id: 116,
    name: "Habanero",
    code: "WCHB",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "Habanero",
    sequence: 999
  },
  {
    id: 121,
    name: "Spinix",
    code: "WCSpinix",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "Spinix",
    sequence: 999
  },
  {
    id: 142,
    name: "FiveG",
    code: "FiveG",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "5G",
    sequence: 999
  }
];

export const LIVECASINO_LIST = [
  {
    id: 123,
    name: "Evo",
    code: "WCEvo",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "LIVE",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "Evolution",
    sequence: 1
  },
  {
    id: 4,
    name: "Awc",
    code: "AWC",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "LIVE",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "Sexy",
    sequence: 999
  },
  {
    id: 5,
    name: "Ezugi",
    code: "EZUGI",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "LIVE",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: null,
    sequence: 999
  },
  {
    id: 100,
    name: "WCOT",
    code: "WCOT",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "LIVE",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "One Touch",
    sequence: 999
  },
  {
    id: 143,
    name: "WCPP",
    code: "WCPP",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "LIVE",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: "Evolution",
    sequence: 999
  }
];
export const SPORT_LIST = [
  {
    id: 133,
    name: "LuckySport",
    code: "LuckySport",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SPORT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: null,
    sequence: 999
  },
  {
    id: 95,
    name: "BTI",
    code: "BTI",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SPORT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: null,
    sequence: 999
  },
  {
    id: 50,
    name: "SABA",
    code: "SABA",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SPORT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: null,
    sequence: 999
  }
];
